include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    # Error rules
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements

    # Style rules
    - always_declare_return_types
    - avoid_catching_errors
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_returning_this
    - avoid_void_async
    - directives_ordering
    - omit_local_variable_types
    - parameter_assignments
    - prefer_asserts_with_message
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_relative_imports
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unawaited_futures
    - use_if_null_to_convert_nulls_to_bools
    - use_string_buffers

    # Disabled rules (too strict or not always applicable)
    # - avoid_catches_without_on_clauses (sometimes catching all exceptions is intentional)
    # - avoid_dynamic_calls (necessary when working with JSON/dynamic data)
    # - cascade_invocations (not always clearer)
    # - discarded_futures (fire-and-forget is sometimes intentional)
    # - lines_longer_than_80_chars (too restrictive for modern screens)
    # - prefer_expression_function_bodies (block bodies can be clearer)
