name: firebase_functions_genkit
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/invertase/firebase-functions-dart

publish_to: none

workspace:
  - example

environment:
  sdk: ^3.10.0

dependencies:
  firebase_functions:
    git:
      url: https://github.com/firebase/firebase-functions-dart/
  genkit: ^0.12.1
  meta: ^1.18.1

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2

dependency_overrides:
  google_cloud_firestore:
    git:
      url: https://github.com/firebase/firebase-admin-dart/
      path: packages/google_cloud_firestore